### ISSUE TITLE
Gem is not working with polarssl 1.3.10

### ISSUE THREAD

**Issue by jvanbaarsen** [michiels/polarssl-ruby#9]
When trying to install on OSX yosemite (10.10.4) with polarssl 1.3.10 installed, I get the following error:

```
Fetching: polarssl-1.0.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing polarssl:
	ERROR: Failed to build gem native extension.

    /Users/jeroen/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150726-44797-1s35712.rb extconf.rb
checking for polarssl/entropy.h... yes
checking for entropy_init() in -lpolarssl... no
libpolarssl is missing.  please install libpolarssl
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jeroen/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
	--with-polarssl-dir
	--without-polarssl-dir
	--with-polarssl-include
	--without-polarssl-include=${polarssl-dir}/include
	--with-polarssl-lib
	--without-polarssl-lib=${polarssl-dir}/lib
	--with-polarssllib
	--without-polarssllib

extconf failed, exit code 1

Gem files will remain installed in /Users/jeroen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/polarssl-1.0.1 for inspection.
Results logged to /Users/jeroen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/polarssl-1.0.1/gem_make.out
```

**Comment by jvanbaarsen** [comment]
A temporary work around (to install polarssl 1.3.9 on your OSX machine):

```shell
$ cd $( brew --prefix )
$ git checkout 8a765c123fc2b9b1cb87a62fd514331b3d00a4fe Library/Formula/polarssl.rb
$ brew install polarssl
```

If you get the error:
```
Error: polarssl-1.3.10 already installed
To install this version, first `brew unlink polarssl'
```

Run: `$ brew unlink polarssl`

**Comment by jvanbaarsen** [comment]
I've been looking at the different versions in Polarssl, the weird thing is, the check that it is failing on:

```ruby
# ext/polarssl/extconf.rb:42
unless find_library('polarssl', 'entropy_init')
  abort "libpolarssl is missing.  please install libpolarssl"
end
```
the `entropy_init` method has not change since 2011 or so, so it should be exactly the same between 1.3.9 and 1.3.10. But still it is failing on that part somehow.

@michiels Did you run into this before?

**Comment by michiels** [comment]
@jvanbaarsen I have not. I'm debugging this now!

**Comment by michiels** [comment]
I have an assumption of what is going wrong: 

PolarSSL was renamed to mbed TLS. It is possible that "polarssl" library does not exist anymore and that from mbed TLS 1.3.10 we need to use "mbedtls" or something here.

**Comment by michiels** [comment]
I can confirm that the rename of the library seems to be the cause. In `ext/polarssl/extconf.rb` this works:

```
unless find_header('polarssl/entropy.h')
  abort "libpolarssl is missing. please install libpolarssl"
end

unless find_library('mbedtls', 'entropy_init')
  abort "libpolarssl is missing.  please install libpolarssl"
end
```

And the current version does not:

```ruby
unless find_header('polarssl/entropy.h')
  abort "libpolarssl is missing. please install libpolarssl"
end

unless find_library('polarssl', 'entropy_init')
  abort "libpolarssl is missing.  please install libpolarssl"
end
```

Since the library was renamed. Maybe it would be better to deprecate this repository and gem, and rename everything to `mbedtls-ruby` which would be supported from mbed TLS version 1.3.10 and higher. Or we can ask the maintainer (someone at ARM) if it's possible to provide backward compatibility in some way.

**Comment by michiels** [comment]
I just pushed the PR that should add short-term support for PolarSSL and the new mbed TLS library naming.

**Comment by michiels** [comment]
Gem version 1.0.2 has been pushed to RubyGems including this fix! Hope this helps :) 

https://rubygems.org/gems/polarssl/versions/1.0.2

**Comment by jvanbaarsen** [comment]
@michiels I think deprecating would be best. Lets release a new gem for the new library.
